### ISSUE TITLE
Gigabytes of discovery traffic with redis discovery

### ISSUE THREAD

**Issue by orgalaf** [dashersw/cote#172]
I am using redis for discovery in production and getting gigabytes of traffic for discovery alone? What am I doing wrong?

- I have about 300 services running 
- 10 servers with Responders and all the rest with Requesters

Could this be related to #171 ?
What other information can help?

thanks

**Comment by orgalaf** [comment]
Just to follow up. After deployment, it looked like discovery was failing or unstable. Services constantly going offline/online all over the place. 

We reduced the helloInterval to 1 minute to reduce hello traffic. Could that be causing other problems?

**Comment by orgalaf** [comment]
More info. While redis network in for hello traffic was about 350MB/minute, network out was 12.5GB/minute. I'm guessing this is due to using the pubsub system and broadcasting each incoming message many times to all the subscribers.

Would the discovery performance be orders of mag better over multicast/broadcast?

Is cote supposed to handle this many services discovering each other?

**Comment by dashersw** [comment]
Hi there! 300 services is a hefty number! I would recommend to actually implement an overlay network instead of using Redis. However, the mechanism is pretty much the same: only the hello messages are broadcast, not every message. Once the services discover each other, connection happens between individual services. Reducing the helloInterval definitely helps with the network chatter, as the default is 3 seconds which means if services don't hear from each other every 3 seconds they declare the other one dead.

The performance would be much better over broadcast in a network router that originally supports broadcast, because it would be a hardware based solution. With an overlay network like Weave, it's still supposed to be better than Redis.

Cote is designed to handle many services, although I only tested up to a 100 services talking to each other. At some point in your design you might think about fragmentation through keys and namespaces. Another advanced configuration if you have multicast is fragmentation by multicast IP, so you (kind of) build your own gateways inside the cote network which distribute the traffic over different multicast networks.

We can always chat on our slack.
