### ISSUE TITLE
Using across multiple datacenters with exact IP's of instances

### ISSUE THREAD

**Issue by gnostis** [dashersw/cote#173]
I have multiple instances running on different cloud providers. What would be the simplest way to configure cote components to communicate each other specifying some list of all my instances IP's.

**Comment by dashersw** [comment]
You need a shared redis instance. As long as you pass in the redis configuration (probably including `DISCOVERY_HOSTNAME`), nodes will discover each other.

**Comment by drubin** [comment]
Are the IP's public or private? 

I mean do you run a peer'ed network or IPSEC tunnel between the cloud providers and have all internal IP's route-able.

If you are trying to use the public IP's this is a total no go since cote assumes a private network for security and exposing your services to the public internet would be a huge security risk.

**Comment by gnostis** [comment]
I just thought it might be some other way possible without redis. Yes, it's public, but luckyly no critical info at all. Btw maybe there is some theoretical risks like DDoS or sending third party data to services.

**Comment by dashersw** [comment]
If you can get an overlay network working between these two cloud providers to support IP broadcast, you can get by without using redis.
