### ISSUE TITLE
time-service.js and client.js not working

### ISSUE THREAD

**Issue by nanetnanet** [dashersw/cote#229]
Downloaded cote-master.zip
Unzip to folder.
npm install.
create sample time-service.js
create client.js

node time-service.js (running)
node client.js (running but no response, I understood to give time for time-service.js ready. I also modify client for requesting every 1000ms and console log confirmed requests every 1000ms)

So I run >npm test
found errors
(I'm using node v.12.19.0)

![image](https://user-images.githubusercontent.com/73052880/96360606-d5f73e80-1148-11eb-9cac-3ddba4734480.png)

**Comment by kerimhudson** [comment]
I was trying this out yesterday and noticed that the callback should take two arguments, an err and a res value. So it works when doing the following.

```
const cote = require('cote');
const timeService = new cote.Responder({ name: 'Time Service' });

timeService.on('time', (req, cb) => {
    cb(undefined, new Date());
});
```

**Comment by dashersw** [comment]
Hello, I tried running your code examples and what we have pointed out in the README — I believe this works well for me, I haven't run into an issue like you mentioned.

If the problem still persists for you, I would be grateful if you could create a repository to replicate the issue.

**Comment by kerimhudson** [comment]
Hey, I'm not the original poster but  I've tried since replicating this issue again and I'm not able to replicate it anymore and get the expected outcome. 

I think my issue stemmed more from the type definitions expecting an error and a result in the callback, and not allowing only for a result, so is more an issue with that package, so in turns I assumed that should be the default behaviour. 

![Screenshot 2020-11-16 at 09 54 21](https://user-images.githubusercontent.com/31065041/99238504-b6a80b80-27f1-11eb-8725-092f607f937b.png)

**Comment by dashersw** [comment]
Thank you 🙏 cote doesn’t have official type information yet—so there might be inconsistencies.
