### ISSUE TITLE
Problem linking more then 2 services

### ISSUE THREAD

**Issue by finalclass** [dashersw/cote#32]
I'm new to cote and maybe I'm missing something but I can't make more then 2 services to work.

Here is an isolated example:

**index.js**
```js
var cote = require('cote');
var SERVERS = [
    'server0',
    'server1',
    'server2'
];
var client = new cote.Requester({
    name: 'index.js',
    requests: SERVERS
});

function nextRequest(i) {
    i = (i % SERVERS.length);

    console.log('Request to server' + i);
    client.send({type: 'server' + i}, function (response) {
        console.log('response', response);
    });

    setTimeout(function () {
        nextRequest(i + 1);
    }, 1000);
}

client.on('ready', function () {
    nextRequest(0);
});
```

**server0.js**

```js
var cote = require('cote');
var server0 = new cote.Responder({name: 'server0', respondsTo: ['server0']});

server0.on('server0', function (req, cb) {
    cb('server0 response ' + new Date());
});
```

**server1.js**
```js
var cote = require('cote');
var server1 = new cote.Responder({name: 'server1', respondsTo: ['server1']});

server1.on('server1', function (req, cb) {
    cb('server1 response ' + new Date());
});
```

**server2.js**
```js
var cote = require('cote');
var server2 = new cote.Responder({name: 'server2', respondsTo: ['server2']});

server2.on('server2', function (req, cb) {
    cb('server2 response ' + new Date());
});
```

To run it do:
```bash
npm install cote
node index.js &
node server0.js &
node server1.js &
node server2.js &
```

Or just run in different terminal windows.

When I change `SERVERS` list in index.js file to just one server (server0) for example and run only `node index.js` and `node server0.js` then I got response for every request. Whenever I'm enabling more servers I'm starting to loose responses.

I'm using cote@0.9.2 and node@6.5.0
Am I missing something?

**Comment by dashersw** [comment]
Hello!

`respondsTo` field is utilised for Sockend services to bind to socket.io messages coming from clients. It doesn't affect requester and responder communication.

Currently there's no way to use one requester with multiple, different responders. A better way is to utilise keys for service segregation:

*index.js*
```js
var cote = require('cote');

var clientA = new cote.Requester({
    name: 'index.js',
    key: 'server0'
});

var clientB = new cote.Requester({
    name: 'index.js',
    key: 'server1'
});

var clientC = new cote.Requester({
    name: 'index.js',
    key: 'server2'
});

var clients = [clientA, clientB, clientC];

function nextRequest(i) {
    i = (i % clients.length);

    console.log('Request to server' + i);
    clients[i].send({type: 'server' + i}, function (response) {
        console.log(i, 'response', response);
    });

    setTimeout(function () {
        nextRequest(i + 1);
    }, 1000);
}

clients[0].on('ready', function () {
    nextRequest(0);
});
```

*server0.js*
```js
var cote = require('cote');
var server0 = new cote.Responder({name: 'server0', key: 'server0'});

server0.on('server0', function (req, cb) {
    cb('server0 response ' + new Date());
});
```

*server1.js*
```
var cote = require('cote');
var server1 = new cote.Responder({name: 'server1', key: 'server1'});

server1.on('server1', function (req, cb) {
    cb('server1 response ' + new Date());
});
```

*server2.js*
```
var cote = require('cote');
var server2 = new cote.Responder({name: 'server2', key: 'server2'});

server2.on('server2', function (req, cb) {
    cb('server2 response ' + new Date());
});
```

Note that an unspecified (null) key is still a valid key. So if you don't specify any keys (or namespaces) as in your example, a requester will connect to all of the responders with a null key. Therefore you start losing messages; because a `server0` request would also go to a `server1` responder.

Cote is designed to be a mesh network with interchangeable parts. Therefore any connection between nodes of these two roles assume that both nodes behave the same. A responder with key `foo` should act (and reply to the same messages) as another responder with the same key. Again; an unspecified key is still a valid key.

**Comment by finalclass** [comment]
Now it works perfectly. Thank you for this explanation. It wasn't clear for me from the documentation.

**Comment by dashersw** [comment]
I'm glad! Yes, we should update the documentation to feature keys and namespaces in more depth!
