### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by dulichan** [dashersw/cote#49]
Is there any plans to add TypeScript support to cote ? (With types?)

**Comment by Robophil** [comment]
with node supporting **es6** a bit more with each release, would that still be necessary?

**Comment by dashersw** [comment]
@Robophil it would bring in type safety and code completion for TS users and modern IDEs.

@dulichan it's not a priority for me right now, but I would love if someone tackled this problem.

**Comment by Robophil** [comment]
True @dashersw, but you can publish typings for your projects without writing it in typescript. 
I see a lot of that now when using **vscode**. IDE's are smart to work with typings. eg express, node, etc see [typings](https://github.com/typings/typings), [definatelytyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by dashersw** [comment]
@Robophil exactly! that's what I understood from "typescript support", just adding the typings. cote is written in ES6, and we will never rewrite it in TS.

**Comment by makepost** [comment]
Have a look at https://github.com/makepost/microservice-playground

Responder and Requester remind me of Service and Inject from typedi

So I applied decorators, metadata, proxies and async/await to get a similar API

Brings my services type safety and code completion in VS Code

Has Publisher, Requester, Responder and Subscriber

I want to focus on logic and avoid introducing extra names

So it uses names of decorated classes as both `key` and `name`

The latter, `name`, is prefixed by e.g. `Publisher--`

If anyone is interested I can make a npm package

**Comment by dulichan** [comment]
It would be awesome if you can publish this as a typing to @types repo.

**Comment by makepost** [comment]
Published definitions as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17373

Install with `yarn add @types/cote`

The utils I mentioned earlier make use of the definitions now

I adapted examples and published the package as well: https://github.com/makepost/nyan-cote

**Comment by dashersw** [comment]
Hello @makepost, thanks for the immense effort! This is a nice beginning, and I would have loved if we worked together on this — the typings have some errors and shortcomings and now since they are in DefinitelyTyped, they are kind of *the* go-to typings.

Here are some of my initial observations:

- There should be no rigid definition of a `cote.Action` other than the requirement that it's an object (record types in JSDoc) with a `type` property. It's not an internal class and shouldn't be called as if so.
- `Advertisement` differs from type to type, `subscribesTo` shouldn't be an option for a responder.
- There are about 10 other `discoveryOptions` and now they are hidden.
- The classes actually inherit from `EventEmitter2` and therefore also expose its API.
- There are missing classes: `TimeBalancedRequester` and `PendingBalancedRequester`.
- As you've mentioned this only takes into account Promises, but the API also works with callbacks.
- There are certain pre-built events that the user can listen to on every component, like `cote:added` and `cote:removed`.

Finally, about nyan-cote: `key`'s can't be automatically deduced from class names, because if a `Requester` and a `Responder` have different keys, they won't be able to communicate.

**Comment by makepost** [comment]
Thanks for the feedback

`@types/cote` has just updated

I addressed all the issues you mentioned

How do I improve `nyan-cote`?

Example services follow `cote` README and are able to communicate

For `Responder`, the key is its own class name

For `Requester`, the key is the class name of the `Responder` it talks to
