### ISSUE TITLE
How is it achieving  Fault tolerance (Documentation)

### ISSUE THREAD

**Issue by deresegetachew** [dashersw/cote#65]
I couldn't find any details on how its achieving Fault tolerance ; I think it would be help full if we had a brief description of how that is achieved.

**Comment by TomKaltz** [comment]
+1

**Comment by dashersw** [comment]
cote has a simple mechanism for this — when there are no responders available, requesters internally queue messages (in memory). Whenever a new responder comes online, they flush the messages they kept to themselves.

This basically means that even if responders die (even for deployment) no requests will be lost. One thing to note here is; there are no timeouts. This is simply because cote is to be used in a dynamic and self-healing environment: there shouldn't be a long period of time where even a single responder is not online.

Another important point is a responder may still crash after successfully receiving a request. cote doesn't guarantee the completion of execution, but only the delivery of the message. Therefore, this type of a crash scenario is not supported.

**Comment by Xstoudi** [comment]
Would be great to queue messages with bee-queue.

**Comment by dashersw** [comment]
It would be an overkill for cote — and it would require redis. cote is a zero-dependency approach and is completely distributed. A central redis server breaks this philosophy.

**Comment by Xstoudi** [comment]
Yeah but you allow the usage of redis, so why not allow bee-queue in an optional way.
