### ISSUE TITLE
Can this actually be used in Kubernetes?

### ISSUE THREAD

**Issue by NickyTope** [dashersw/cote#66]
I am trying to  implement cote in kubernetes on IBM bluemix and am having alot of trouble getting it to work.

The bluemix kubernetes implementation has Calico plugin at network layer and Pods can definitely access each other via IP.

I have put a redis service in place and set cote to use that for discovery which works:
```
2017-09-13T05:23:41.920741203Z core space requester > service.online idea service space responder#7528508b-a087-414e-ade8-2a95825472e1 on 8002
```

however once it starts actually messaging it seems to drop back to hostnames that do not resolve inside kubernetes, e.g.
```
2017-09-13T05:23:46.925401243Z Error: getaddrinfo EAI_AGAIN idea:8000
2017-09-13T05:23:46.925441235Z     at Object._errnoException (util.js:1041:11)
2017-09-13T05:23:46.925447197Z     at errnoException (dns.js:58:15)
2017-09-13T05:23:46.925452669Z     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
```

I've trawled through the implementation of node-discover and can see the hostname getting encoded in the message but I'm unclear if that hostname is used to respond.

Is there a way to insist on using IP addresses for communication rather than hostnames or am I looking down the wrong path here?

**Comment by dashersw** [comment]
Apparently, the host name configuration was a preliminary move and a mistake for K8S. One thing you can do to bypass it and use IP addresses again is to pass in a config object when you require cote (it needs to be done only once, other requires don't need it);

```
const cote = require('cote', { useHostNames: false });
```

Having said that, please take a look at https://github.com/dashersw/cote-workshop/pull/5 which details a K8S setup. It will be official soon.

**Comment by NickyTope** [comment]
Thanks for your quick reply!!

Unfortunately neither of these approaches seem to work for me.

I have tried installing weave CNI plugin however it does not appear to be compatible with the bluemix implementation of Kubernetes. and the Calico implementation there does not support multicasting.

The ```useHostNames: false``` change has stopped the error I was seeing however no messages are being received (I assume this is because the reported address when using redis for discovery is 0.0.0.0).

To check that anything at all is working, I have configured a kubernetes subdomain as per their doco (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/), using this subdomain the pods can see each other using hostname.subdomain however I can't see a clear way to get cote to use that (other than forking cote and node-discover and change the hostName var to accept an environment variable).

Any advise/help you can provide would be amazing!

**Comment by NickyTope** [comment]
Would you consider changing or accepting a Pull Request in node-discover? something to the effect of:
```
(lib/network.js#11)
var hostName = process.env.DISCOVERY_HOSTNAME || os.hostname();
```

**Comment by dashersw** [comment]
@drubin what do you think about the issue?

@NickyTope if we can't find a solution that works here, we could have an environment variable as you suggested to set the discovery names of each service individually.

**Comment by drubin** [comment]
@NickyTope I also had a similar issue with weave networking lucky for me it was simple as switching from broadcast to multicast. (and reading the docs again).

I will try next week to see if I can get a cluster running Calico and see if I can get a setup working.

As for the hostname approach, k8s and hostnames are a little iffy since a pod's DNS is pretty much its IP with -'s in it. I had a similar suggestion of using the below to inject the discover_name but I found a work around using Weave net.

```
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```

Also from https://docs.projectcalico.org/v2.5/usage/openstack/semantics 

> Note: Calico’s connectivity design, based on IP routing, allows unicast IP and anycast IP. Anycast IP also requires support for allowed-address-pairs, or some other way of assigning the same IP address to more than one instance; work for allowed-address-pairs support is in progress at https://review.openstack.org/#/c/344008/. Multicast IP support is on our roadmap but not yet implemented. Broadcast IP is not possible because it depends on L2 adjacency.

It seems like a safe bet will be to make the redis integration work with correct ips.

**Comment by NickyTope** [comment]
Thanks for looking @drubin and @dashersw I'm glad that what I've been coming up with is similar to what you have found.

I have currently deployed successfully using a fork of node-discover (and cote to point at it) with the ```env.DISCOVERY_HOSTNAME || os.hostname()``` change above and am using pretty much exactly what you put above for the Deployment yaml:
```
- name: DISCOVERY_HOSTNAME
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```

I also found that multicast is on the way for Calico (and many other of the available network plugins for kube), so am looking forward to going back to less configuration for cote in future, however in my current situation (deployment via IBM bluemix) I don't have enough control over the host environment to change network plugins so would really appreciate you guys considering this change, or perhaps you can see a better way to go back to ```useHostNames: false``` in combination with redis discovery and an environment variable so the correct IP can be reported to redis?

Really appreciate you guys looking into this!

**Comment by drubin** [comment]
I think the easiest approach for this would be what you have suggested above. 

Also there potentially 2 ways of getting the IP address

1. From the packet. (I found with k8s setup with broadcast the source address is the internal router at not the actual pod.)
2. From the pod its self and send it through. (Like your method above)

The issue with `useHostNames: false` with redis is that each node has to pick what their IP (because of the router issue above) should be and most pods have multiple IP addresses, `0.0.0.0`, `127.0.0.1`, their internal network, some cases IPV6 address and so on. So I originally had a proposal to "just pick the first IPV4 address that is a not internal" but I think this is also pretty error-prone for a fallback.

I think if the autodiscovery doesn't work it makes the most sense to allow the operator to explicitly provide a config + broker (in this case redis). 

Obviously, this is a fallback/worst case but in my opinion, provides way more stable predictable method of discovery than trying to build a few more heuristics that might not work all the time anyway.

What are your thoughts? @dashersw @NickyTope

**Comment by NickyTope** [comment]
Thanks for your thoughts and comments.

Totally agree that this is a fallback / worst case scenario for cote discovery but it allows at least a working environment in a network where the current options are restricted or not viable.

The changes mentioned above have been implemented in my dev environment and are working flawlessly.

@dashersw I have created a pull request with the above in your fork of node-discover for your consideration.

I still don't think it's ideal that I'm sending the IP and calling it 'hostname' however as @drubin mentioned above, that is part of the way hostnames can be assigned in k8s anyway and the proposed change does not at all mention sending the IP, you could also setup a k8s subdomain as mentioned above and provide something like <service>.<subdomain> as the hostname.

**Comment by LeoVS09** [comment]
Hello. 
I'm trying use cote in k8s cluster. But service discovery not work. I used `DISCOVERY_HOSTNAME`  and
```
const cote = require('cote', { useHostNames: false });
```
Also start [workshop example cluster](https://github.com/drubin/cote-workshop/tree/k8s-example), but services also not find each other.
May be need additional configuration for k8s?

**Comment by drubin** [comment]
@LeoVS09 as mentioned https://github.com/dashersw/cote-workshop/pull/5#issuecomment-482807015 

Right now the easiest way to get this working in either docker-swarm or k8s is to use the redis service discovery (with DISCOVERY_HOSTNAME env param).

I can update the example workshop to work k8s with redis, but will only get to that next week.

**Comment by LeoVS09** [comment]
Thank you! With redis all start working!

**Comment by orgalaf** [comment]
I set up a minimal kubernetes cluster with weave network. discovery seems to be working but the actual messages don't get through. what could be the problem? is there some way to turn on more verbose logging?

**Comment by drubin** [comment]
@orgalaf  this should help 
https://github.com/dashersw/cote#controlling-cote-with-environment-variables

`COTE_LOG=true`  as an env var. 

I had a similar issue it was trying to use BROADCAST or ANYCAST instead of `COTE_MULTICAST_ADDRESS`.

@orgalaf what is your kubernetes cluster setup? How did you set it up, what is it running on?

**Comment by orgalaf** [comment]
Hi, so after more reading through this issue I got it to work on a local
cluster with weave + DISCOVERY_HOSTNAME as detailed above +
COTE_USE_HOSTNAMES true. Did not need to switch to multicast or use  redis.
Today will try it on a cluster in aws.
