### ISSUE TITLE
Explanation on doc.

### ISSUE THREAD

**Issue by Robophil** [dashersw/cote#68]
Hi @dashersw,

I just need more light be shed on this part of the documentation

> > Note: By default, every `Requester` will connect to every `Responder` it
> discovers, regardless of the request type. This means, every `Responder` should
> respond to the exact same set of requests, because `Requester`s will
> load-balance requests between all connected `Responder`s regardless of
> their capabilities, i.e, whether or not they can handle a given request.
> 
> If you have multiple `Responder`s with varying response handlers, you will
> experience lost requests. In cote, this separation between responsibilities is
> called segmentation, or partitioning. If you wish to segment your requests in
> groups, you can use `key`s. Check out [keys](#keys) for a detailed guide on how
> and when to use segmentation.

Also, could you explain more on **key**, **namespace**, and **environment**? When to use each.
Seems to me that **key** and **environment** are interchangeable

**Comment by dashersw** [comment]
Hello!

1) Think of a responder that can handle messages of type A. Think also that you have another responder that can handle messages of type B. Now if you create a requester, and there are no key / namespace / environment configuration involved in this setup, that requester will connect to both of these responders.  So it will load balance every request between these two, and the first responder will get messages of type both A and B. Since it doesn't know what to do with messages of type B, you will see lost requests.

2) They are semantically the same. However, there are minor differences. A namespace maps directly to socket.io namespaces, therefore it should be used when there are Sockend components involved. This way, you can expose functionality to the frontend. A key is a component configuration, so has to be set per component instance. An environment is mainly passed in as an environment variable or is given as a general config as in `require('cote')({ environment: 'test'})`. Think of environments as general as your test or prod environments. Keys could be used in a more granular fashion, for example for each domain in DDD; e.g. payment, catalog, cart.

I hope this helps. Let me know if it's still unclear.

**Comment by Robophil** [comment]
What about `respondsTo` in responders?
And can components in different **environments** see each other?

**Comment by dashersw** [comment]
`respondsTo` is used by the Sockend component to detect which messages a responder could handle, so that it can channel those from the frontend. Other than that, it's mostly used for documentation purposes, like API footprints.

Technically, components in different environments _see_ each other through broadcast / multicast (if they also share the same broadcast / multicast address). But they respect the environment / key / namespace configuration and just ignore each other.

**Comment by Robophil** [comment]
Cool... thanks @dashersw for the help.

**Comment by Robophil** [comment]
Similar to `respondsTo` in **Responders**, `requests: ['randomRequest']` in **Requesters** are also used for Sockend Components right?

**Comment by dashersw** [comment]
No, actually `requests` is only for documentation, it's not used anywhere.

**Comment by Robophil** [comment]
Ok. Noted.
