### ISSUE TITLE
Responder and Requester Problems

### ISSUE THREAD

**Issue by chameleonbr** [dashersw/cote#70]
I created 2 services on different projects and another project to call this:
 ```javascript

const cote = require('cote')
//responder 1
const responder1 = new cote.Responder({
    name: 'resp1'
});
//responder 2
const responder2 = new cote.Responder({
    name: 'resp2'
});
//responder1 -> mtd1
responder1.on('mtd1', (req, cb) => {
    cb('OK1!');
});
//responder2 -> mtd2
responder2.on('mtd2', (req, cb) => {
    cb('OK2!');
});

//creating requester
const requester = new cote.Requester({
    name: 'req1'
});

const request = {
    type: 'mtd1',
    val: 'test'
};


setInterval(() => {
    console.log('calling...')
    requester.send(request, (res) => {
        console.log(res);
    });
}, 1000);
```
When I call mtd1, only half of the answers come back. 
If I delete responder2 all responses come back.
If I create responder3, only 33% of requests come back.

What am I doing wrong? Thank you.

**Comment by dashersw** [comment]
By default, all the messages, regardless of type, go to all Responders. So each Responder should know how to respond to every request. If you want to segregate responsibilities so that different Responders should be able to respond to different types of requests, you should use `key`s. You can find more about keys in the readme.
