### ISSUE TITLE
Gossip protocol as replacement for redis discovery?

### ISSUE THREAD

**Issue by thelinuxlich** [dashersw/cote#79]
Moleculer is a similar project to cote, take a look at this issue:

https://github.com/ice-services/moleculer/issues/46

**Comment by dashersw** [comment]
As detailed here https://www.youtube.com/watch?v=9yJ_Lfw-JCs this gossip protocol requires a direct socket connection between services and service discovery gets slower the bigger the number of services get. It takes 26 seconds for 50 services; which is almost at the limits of a request timeout. Furthermore, this implementation at moleculer still uses UDP multicast, so wouldn't still work in a cloud environment.

I don't see the point in that, when all brokers exchange UDP messages, they still need a gossip protocol to _transfer node lists_. A gossip protocol makes more sense as a _communication protocol_ instead of a _discovery protocol_, where two services A and B can talk to each other without a direct connection. The intermediary services propagate messages from A to B, so A connects only to a handful of others despite being able to talk to many others.
