### ISSUE TITLE
Provide a time feature in Requestor instance

### ISSUE THREAD

**Issue by katturajam** [dashersw/cote#83]
I am very happy but we have need a promise with timeout for the requester instance otherwise its keep on waiting for that responder service online.

**Comment by dashersw** [comment]
Currently cote doesn't offer timeouts out of the box; mostly because we don't want to be opinionated about how to handle timeouts. There are two scenarios;

a) you've sent the request, the requester didn't get it, so there's a timeout and it's safe to do the request again.
b) you've sent the request, the requester did get and process it but failed to respond. it may not be safe to do the request again.
c) you've sent the request, the requester did get and process it, and responded, but there was a network error and your response would arrive later. it may not be safe to do the request again.

we could potentially implement a timeout with a default of Infinity, but that would increase complexity. However, I'm still open to further discussion.

**Comment by buckle2000** [comment]
```
new Promise((resolve, reject) => {
    client.send({ type: 'time' }, resolve);
    setTimeout(reject, 1000);
}).then(time => {
    console.log(time)
}).catch(error => {
    console.error(error)
})
```

**Comment by dnunes** [comment]
Hey, @dashersw, just found out about the project. Some time ago I though about developing something using [dnode](https://www.npmjs.com/package/dnode) but didn't really had time to develop the idea. Very nice to see something working (and on a very mature stage, as it seems).
One thing I noticed: shouldn't the issues be closed after responding? There are many issues here that are invalid and as they are not closed the project looks like it has a lot of issues/problems/bugs/errors. For anyone researching the options, it would be cool to be able to quickly evaluate the real situation and the maturity of the project without having to really read through the old/invalid opened issues.

Also: any thoughts on dnode? Is it possible to implement the same idea using it?

Thanks for the great project.

**Comment by dashersw** [comment]
You are right. I thought of keeping them open, as they serve the purpose of a community generated FAQ. But you are right, I should close the old issues.

Dnode, as far as I know, is great for bridging two streams. It requires a lot of other infrastructure to build auto-discovery and all the other features into it. So I would say it’s not worth the effort.
