### ISSUE TITLE
I don't understand the key concept

### ISSUE THREAD

**Issue by sdeceuninck** [dashersw/cote#96]
Hello,

I should miss understand the key concept.
I try using the same key for a responder and a requester on 2 apps
```
//Initiate the requester
const Requester = new cote.Requester({
   name: "TefRequester",
   key: "CORE"
})

// Initiate the responder
const Responder = new cote.Responder({
   name: "TefResponder",
   key: "CORE"
})
```
Another app is doing the same (only the name changes). My goal is that the 2 apps consum the service and respond to the service of the other app .. but it doesn't work.

To make it work, I need to change the KEY.
1.First app has a responder on a KEY and the second app the requester on the same key
2.First app has a requester on an other key and the second app the responder on this second key

Why can't I have the same key for all responders and requesters ? If yes, it can be a dfficult to manage when there is a lot of services.

Thanks

**Comment by dashersw** [comment]
You can have the same key for every component. But if you share the same key among different components, make sure the Responders can respond to all the events.

if RequesterA requests X and Y, and if ResponderA responds to X and Y, this will work.
if RequesterB requests U and T, and if ResponderB responds to U and T, and these 4 components share the same key, then RequesterA will send X and Y to ResponderB and wait for a response. Since ResponderB doesn't know how to respond to these events, this setup won't work.

In fact, keys are used just for the purpose of segregating request types, as in this case.

**Comment by sdeceuninck** [comment]
Hello,

sorry for my late answer.
Thanks for your explanation.
